resources:
  - name: code_analysis_resource
    type: CodeAnalysis
    configuration:
      integration: sonar_int
  - name: code_gitrepo
    type: GitRepo
    configuration:
      path: creepy-pirate/jfrog-pipelines-test-yamls
      gitProvider: deepak_git
      branches:
        include: master
  - name: code_gitrepo_standalone
    type: GitRepo
    configuration:
      path: creepy-pirate/jfrog-pipelines-test-yamls
      gitProvider: deepak_git
      branches:
        include: master

pipelines:
  - name: code_analysis_pipe
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          env2: "test_p2"
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          inputResources:
              - name: code_gitrepo
              - name: code_gitrepo_standalone
          outputResources:
              - name: code_analysis_resource
        execution:
          onExecute:
            - end_step failure
          #   - write_output code_analysis_resource "git_resource=code_gitrepo"
          # onSuccess:
          #   - echo "Ran in onSuccess"
          #   - write_output code_analysis_resource "git_resource=code_gitrepo"
          onFailure:
            - echo "Ran in onFailure"
            - write_output code_analysis_resource "git_resource=hrllo"
     
