pipelines:
- name: update_run_desc
  configuration:
    jfrogCliVersion: 2
  steps:
    - name: test_step
      type: Bash
      execution:
        onStart:
          - echo "chala"
          - update_run_description "updated run descr from onStart section"
        onExecute:
          - update_run_description "updated run descr from onExecute section"
