resources: 
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_xray
      buildName: S_DockerPush_8307_009
      buildNumber: 361420

pipelines:
  - name: test_xray_step_frontend
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: scan
        type: XrayScan
        configuration:
         #inherits all the tags from bash
         failOnScan: true                    # default true
         inputResources:
           - name: myBuildInfo        # required
             trigger: false
        execution:
         onStart:
           - echo "Preparing for work..."
           - echo "Prepping build environment"
         onSuccess:
           - echo "Job well done!"
