resources:
  - name: code_analysis_resource
    type: CodeAnalysis
    configuration:
      integration: sonar_int
  - name: code_gitrepo
    type: GitRepo
    configuration:
      path: creepy-pirate/jfrog-pipelines-test-yamls
      gitProvider: deepak_git
      branches:
        include: master
  - name: code_gitrepo_standalone
    type: GitRepo
    configuration:
      path: creepy-pirate/jfrog-pipelines-test-yamls
      gitProvider: deepak_git
      branches:
        include: master

pipelines:
  - name: code_analysis_pipe
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          env2: "test_p2"
    steps:
      # - name: pre_step
      #   type: Bash
      #   configuration:
      #     outputResources:
      #         - name: code_analysis_resource
      #   execution:
      #     onExecute:
      #       - echo "Ran Code analysis step 1"
      - name: trigger_1
        type: Bash
        configuration:
          inputResources:
              - name: code_gitrepo
              - name: code_gitrepo_standalone
          outputResources:
              - name: code_analysis_resource
        execution:
          onExecute:
            - echo "Ran Code analysis step 2"
            - write_output code_analysis_resource "git_resource=code_gitrepo"
      - name: trigger_2
        type: Bash
        configuration:
          inputResources:
              - name: code_gitrepo_standalone
        execution:
          onExecute:
            - echo "Ran Code analysis step 2"
            - echo "shashank-taliwal"
            # - cd $res_code_gitrepo_resourcePath
            # - git checkout main
            # - touch hello.txt
            # - git add hello.txt
            # - echo "hello" >> hello.txt
            # - git commit -m "added hello.txt"
            # - git push origin main
           
      # - name: trigger_2
      #   type: Bash
      #   configuration:
      #     affinityGroup: trigger
      #     timeoutSeconds: 5
      #     inputSteps:
      #       - name: pre_step
      #   execution:
      #     onExecute:
      #       - echo $resource_new_2_path
